obstacle_range: 3.0
raytrace_range: 3.5

# robot is 0.225 m long (split 9/13.5 from pivot center), and 0.135 m wide
footprint: [[0.09, 0.0675], [0.09, -0.0675], [-0.135, -0.0675], [-0.135, 0.0675]]
#robot_radius: 0.105

inflation_radius: 0.2 #  1.0 way too big for 'roboland'
cost_scaling_factor: 4.0 # 3.0 larger value DECREASES cost value

map_type: costmap
observation_sources: scan
scan: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}